from collections import OrderedDict

PORTS = OrderedDict([
    (20,  'FTP -- Data'),
    (21,  'FTP -- Control'),
    (22,  'SSH Remote Login Protocol'),
    (23,  'Telnet'),
    (25,  'Simple Mail Transfer Protocol (SMTP)'),
    (53,  'Domain Name System (DNS)'),
    (80,  'HTTP'),
    (110, 'POP3'),
    (115, 'Simple File Transfer Protocol (SFTP)'),
    (137, 'NetBIOS Name Service'),
    (139, 'NetBIOS Datagram Service'),
    (143, 'Interim Mail Access Protocol (IMAP)'),
    (150, 'NetBIOS Session Service'),
    (194, 'Internet Relay Chat (IRC)'),
    (197, 'Directory Location Service (DLS)'),
    (389, 'Lightweight Directory Access Protocol (LDAP)'),
    (443, 'HTTPS'),
    (445, 'Microsoft-DS'),
    (546, 'DHCP Client'),
    (547, 'DHCP Server'),
    (1433, 'MS SQL Server'),
    (1434, 'MS SQL Server'),
    (1521, 'Oracle'),
    (1522, 'Oracle'),
    (1525, 'Oracle'),
    (1529, 'Oracle'),
    (3000, 'HTTP (development)'),
    (3306, 'MySQL'),
    (3389, 'Remote desktop'),
    (5432, 'PostgreSQL'),
    (5500, 'TightVNC'),
    (5800, 'VNC'),
    (5900, 'VNC'),
    (8000, 'HTTP (development)'),
    (8080, 'HTTP (development)'),
])
